spring.application.name=financeia-backend

spring.config.import=optional:file:../../.env

# MySQL Configuration (Railway)
spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:32819/railway
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Initialize schema from root database_schema.sql
spring.sql.init.mode=never

# We disable flyway for now so we can use the strict schema
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT secret from .env
jwt.secret=${JWT_SECRET}

# Integracion Backend -> Data Science
financeai.python.command=${PYTHON_COMMAND:../../DataScient/venv/Scripts/python.exe}
financeai.data-science.script=${DATA_SCIENCE_SCRIPT:../../DataScient/src/predict.py}


server.port=${PORT:8080}
